### PR TITLE
Bugfix/for cpp17

### PR DESCRIPTION
**Pull request by Finii**
Two small corrections.

GUL17 is ready, but is depending on these fixes :grimacing:

### CODE REVIEW

**Comment by Finii** [comment]
The workflow throws away (almost) all that is in the GUL17 repo.
Then it fetches GUL14
Converts
And pushes the newly created files back to GUL17

```yaml
name: Autocreate GUL17  
  
on:  
  workflow_dispatch:  
  
jobs:  
  autogen:  
    runs-on: ubuntu-latest  
    steps:  
  
      - name: Check out repo  
        uses: actions/checkout@v3  
  
      - name: Check out GUL14 repo  
        run: |  
          git clone https://github.com/gul-cpp/gul14.git gul14  
          git -C gul14 checkout bugfix/for_cpp17  
  
      - name: Convert for C++17  
        run: |  
          cp -f make_gul17.sh gul14/tools  
          cd gul14/tools  
          ./make_gul17.sh  
  
      - name: Move files to GUL17  
        run: |  
          rm -Rf include src tests debian data examples tools  
          cp -r gul14/include .  
          cp -r gul14/src .  
          cp -r gul14/tests .  
          cp -r gul14/debian .  
          cp -r gul14/data .  
          cp -r gul14/examples .  
          cp -r gul14/tools .  
          cp gul14/README* .  
          cp gul14/meson.build .  
          cp gul14/*.spec .  
  
      - name: Commit updated files  
        uses: EndBug/add-and-commit@v9  
        with:  
          fetch: false  
          add: "['include', 'src', 'tests', 'debian', 'data', 'examples', 'tools', 'README*', 'meson.build', '*.spec']"  
          message: "[ci] Bump release version"  
          committer_name: GitHub Actions  
```

Tags and stuff are not synced.

We can improve if need be, at the moment the converter is sufficient and the tests run ok.

**Review by soerengrunewald — APPROVED** [review]
Looks good to me

**Review by alt-graph — APPROVED** [review]
LGTM.

**Comment by alt-graph** [comment]
> The workflow throws away (almost) all that is in the GUL17 repo. Then it fetches GUL14 Converts And pushes the newly created files back to GUL17

The converter is a great idea. For the time being, we should clearly mark the repository as experimental, though. And maybe remove/replace the README. It contains grossly misleading information as it is ("gul17 is available from vcpkg" etc.).

And we still need to have the discussion about if and when to move to GUL17 with the entire DOOCS codebase.

**Pull request merged**
